### ISSUE TITLE
Simple example failed to run

### ISSUE THREAD

**Issue by Time-Coder** [Time-Coder/Glass-Engine#10]
```python
from glass_engine import *

scene, camera, light, floor = SceneRoam()
camera.screen.show()
```

shows just a white screen and when mouse drag following exception occured:
```
Traceback (most recent call last):
  File "glass_engine\Screens\QtScreen.py", line 332, in paintGL
    should_update_scene = self.renderer.render() or should_update_scene
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "glass_engine\Renderers\ForwardRenderer.py", line 83, in render
    self.draw_opaque()
  File "glass_engine\Renderers\ForwardRenderer.py", line 65, in draw_opaque
    self._draw_opaque()
  File "glass_engine\Renderers\ForwardRenderer.py", line 20, in _draw_opaque
    self.prepare_forward_draw_mesh(True)
  File "glass_engine\Renderers\CommonRenderer.py", line 958, in prepare_forward_draw_mesh
    self.forward_program["camera"] = camera
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "glass\GPUProgram.py", line 133, in __setitem__
    self._uniform[name] = value
    ~~~~~~~~~~~~~^^^^^^
  File "glass\Uniform.py", line 244, in __setitem__
    self._set_atom(atom["name"], atom_value)
  File "glass\Uniform.py", line 283, in _set_atom
    func(location, value)
  File "glass\Uniform.py", line 326, in _set_float
    GL.glUniform1f(location, value)
  File "src\\errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'\xce\xde\xd0\xa7\xb2\xd9\xd7\xf7',
        baseOperation = glUniform1f,
        cArguments = (8, 0.9962515234947205)
)
```

**Comment by Time-Coder** [comment]
Found reason: PySide6 6.7.0 cause this problem. Old version PySide6 (6.6.3 and older) works fine. Will find a way to make compability for PySide6 6.7.0

**Comment by Time-Coder** [comment]
version 0.1.55 fix this bug
