### ISSUE TITLE
AttributeError: 'IntConstant' object has no attribute 'bind'

### ISSUE THREAD

**Issue by hero** [Time-Coder/Glass-Engine#2]
I installed and tested according to the official documentation, and the following error occurred:
```
Traceback (most recent call last):
  File "C:\Users\wuking\Desktop\test.py", line 10, in <module>
    camera.screen.show() # 相机显示屏显示渲染结果
  File "C:\Anaconda3\envs\base\lib\site-packages\glass_engine\Screens\QtScreen.py", line 488, in show
    self.__class__.__base__.show(self)
  File "C:\Anaconda3\envs\base\lib\site-packages\glass_engine\Screens\QtScreen.py", line 273, in paintGL
    should_update_scene = self.renderer.render() or should_update_scene
  File "C:\Anaconda3\envs\base\lib\site-packages\glass_engine\Renderers\ForwardRenderer.py", line 61, in render
    self.update_dir_lights_depth()
  File "C:\Anaconda3\envs\base\lib\site-packages\glass_engine\Renderers\CommonRenderer.py", line 403, in update_dir_lights_depth
    mesh.draw(self.dir_light_depth_program, instances)
  File "C:\Anaconda3\envs\base\lib\site-packages\glass_engine\Mesh.py", line 824, in draw
    program.draw_triangles(self._vertices, self._indices, instances, self.__primitive)
  File "C:\Anaconda3\envs\base\lib\site-packages\glass\ShaderProgram.py", line 813, in draw_triangles
    total, times = self.__preprocess_before_draw(
  File "C:\Anaconda3\envs\base\lib\site-packages\glass\ShaderProgram.py", line 680, in __preprocess_before_draw
    vao.bind()
AttributeError: 'IntConstant' object has no attribute 'bind'
```
**Python version**:  `3.10.13`
**Operation reproduction**
1. Install `Glass-Engine`:
    ```bash
   pip install glass-engine --upgrade
   ```
2. write a `test.py` script on my Desktop:
```python
from glass_engine import *
from glass_engine.Geometries import * # 导入所有的基本几何体

scene, camera, light, floor = SceneRoam() # 创建基本场景

sphere = Sphere() # 创建一个球体模型
sphere.position.z = 1 # 设置球体位置
scene.add(sphere) # 将球体添加到场景中

camera.screen.show() # 相机显示屏显示渲染结果
```

3. Run the `python .\test.py` command, but got the above error message.
4. Also I've test the demo code in IPython, got the same error.

**Comment by Time-Coder** [comment]
Hi, Please try glass-engine version 0.1.51, if the bug still exists, please let me know. Before you install 0.1.51, please remove old version:
```
pip uninstall glass-engine
pip install glass-engine==0.1.51 --upgrade
```

**Comment by Time-Coder** [comment]
long time no response, closed.
