### ISSUE TITLE
ImportError: cannot import name 'Self' from 'typing'

### ISSUE THREAD

**Issue by Time-Coder** [Time-Coder/Glass-Engine#6]
glass-engine version: 0.1.52
python version: 3.9.13
graphics card: AMD Radeon(TM) Graphics
os: windows
bit: 64bits
machine: AMD64

error when run following code:
```python
from glass_engine import *

scene, camera, _, _ = SceneRoam()

camera.screen.show()
```

got following error:
```
Traceback (most recent call last):
  File "test_glass_engine.py", line 1, in <module>
    from glass_engine import *
  File "glass_engine\__init__.py", line 3, in <module>
    from .Scene import Scene
  File "glass_engine\Scene.py", line 1, in <module>
    from .SceneNode import SceneNode
  File "glass_engine\SceneNode.py", line 6, in <module>
    from glass.DictList import DictList
  File "glass\__init__.py", line 3, in <module>
    from .VAO import VAO
  File "glass\VAO.py", line 7, in <module>
    from .GLObject import GLObject
  File "glass\GLObject.py", line 5, in <module>
    from .MetaInstancesRecorder import MetaInstancesRecorder
  File "glass\MetaInstancesRecorder.py", line 1, in <module>
    from .WeakSet import WeakSet
  File "glass\WeakSet.py", line 1, in <module>
    from .WeakRef import WeakRef
  File "glass\WeakRef.py", line 3, in <module>
    from typing import Any, Self, Union
ImportError: cannot import name 'Self' from 'typing' (Python\3.9.13\lib\typing.py)
```

**Comment by Time-Coder** [comment]
[v0.1.54](https://github.com/Time-Coder/Glass-Engine/releases/tag/v0.1.54) fix this bug
