### ISSUE TITLE
zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by Time-Coder** [Time-Coder/Glass-Engine#8]
OS: Linux x86_64 64bits

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wbh/Projects/Glass-Engine/glass/ShaderParser_/ShaderParser_.py", line 69, in glsl_parser
    zip_file = zipfile.ZipFile(self_folder + "/tree-sitter-glsl/src.zip")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/zipfile/__init__.py", line 1341, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.12/zipfile/__init__.py", line 1408, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by Time-Coder** [comment]
v0.1.54 fix this bug
